export const API_ENDPOINTS = {
  CHECK_CODE: 'auth/check-code/',
  FORGET_PASSWORD: 'auth/forget-password/',
  GET_CODE: 'auth/get-new-code/',
  LOGIN: 'auth/login/',
  REGISTER: 'auth/register/',
  RESET_PASSWORD: 'auth/reset-password/',
  UPDATE_PASSWORD: 'auth/update-password/',
  VERIFY: 'auth/verify/',
  CATEGORIES: 'common/categories/',
  CATEGORIES_ALL: 'common/category-parents-image-list/',
  BANNER: 'common/banners/',
  BANNER_RIGTH: 'common/advertisements/',
  FASHION_PRODUCTS: 'common/global/products/',
  PRODUCTS_DETAILS: 'common/product/detail',
  PRODUCTS_DETAILS_SINGLE: 'common/similar/producdts',
  // DIETARY: '',
  // BRANDS: '',
  // PRODUCTS: '',
  // PRODUCT: '',
  // RELATED_PRODUCTS: '',
  // FLASH_SELL_PRODUCTS: '',
  // BEST_SELLER_PRODUCTS: '',
  // NEW_ARRIVAL_PRODUCTS: '',
  // POPULAR_PRODUCTS: '',
  // ELETRONIC_PRODUCTS: '',
  // ELECTRONIC_CATEGORY: '',
  // PHONES_CATEGORY: '',
  // COMPUTER_CATEGORY: '',
  // TOPSELL_CATEGORY: '',
  // CLOTH_CATEGORY: '',
  // SEARCH: '',
  // ORDERS: '',
  // ORDER: '',
  // ORDER_STATUS: '',
  // ADDRESS: '',
  // CONTACT: '',
  // WISHLIST: '',
  // BLOGDETAILS: '',
  // THIS_WEEK_PRODUCTS: '',
  // TOPSELL_PRODUCTS: '',
};
