export const API_ENDPOINTS = {
  CHECK_CODE: 'auth/check-code/',
  FORGET_PASSWORD: 'auth/forget-password/',
  GET_CODE: 'auth/get-new-code/',
  LOGIN: 'auth/login/',
  REGISTER: 'auth/register/',
  RESET_PASSWORD: 'auth/reset-password/',
  UPDATE_PASSWORD: 'auth/update-password/',
  VERIFY: 'auth/verify/',
  CATEGORIES: 'common/categories/',
  CATEGORIES_ALL: 'common/category-parents-image-list/',
  BANNER: 'common/banners/',
  BANNER_RIGTH: 'common/advertisements/',
  FASHION_PRODUCTS: 'common/global/products/',
  PRODUCTS_SECTION_1: 'common/sections/section_1',
  PRODUCTS_SECTION_2: 'common/sections/section_2',
  PRODUCTS_SECTION_3: 'common/sections/section_3',
  PRODUCTS_DETAILS: 'common/product/detail',
  PRODUCTS_DETAILS_SINGLE: 'common/similar/producdts',
  ORDERS: 'common/order-list/',
  ORDERS_CREATE: 'payment/create/',
  ORDERS_DETAILS: 'common/order-detail',
  BRANCHES: 'payment/branches',
  PAYMENT: 'payment/shipping_cost',
  PRODUCTS_MORE: 'payment/more-products-application',
  CONTACT: "common/contact/",
  BRANDS:"common/brands/",
  PROFILE:"auth/profile/"

};
