export const ROUTES = {
  HOME: '/',
  PRODUCT: `/products`,
  CHECKOUT: '/checkout',
  CONTACT: '/contact-us',
  FAQ: '/faq',
  FORGET_PASSWORD: '/forget-password',
  CHANGE_PASSWORD: '/my-account/change-password',
  ORDERS: '/my-account/orders',
  LOGIN: '/signin',
  SIGN_UP: '/signup',
  PRODUCTS: '/products',
  BUNDLE: '/bundles',
  CATEGORY: '/category',
  WISHLIST: '/my-account/wishlist',
};
