export const footer = {
  widgets: [
    {
      id: 1,
      widgetTitle: 'НАШИ СЕРВИСЫ',
      lists: [
        {
          id: 1,
          title: 'Главный',
          path: '/en',
        },
        {
          id: 2,
          path: '/checkout/',
          title: 'Проверить',
        },
        {
          id: 3,
          title: 'ТСС',
          path: '/faq',
        },
        {
          id: 7,
          path: '/contact-us',
          title: 'Связаться с нами',
        },
      ],
    },
  ],
  payment: [
    {
      id: 1,
      path: '/',
      image: '/assets/images/payment/mastercard.svg',
      name: 'payment-master-card',
      width: 43,
      height: 25,
    },
    {
      id: 2,
      path: '/',
      image: '/assets/images/payment/visa.svg',
      name: 'payment-visa',
      width: 42,
      height: 28,
    },
    {
      id: 3,
      path: '/',
      image: '/assets/images/payment/paypal.svg',
      name: 'payment-paypal',
      width: 57,
      height: 32,
    },
    {
      id: 4,
      path: '/',
      image: '/assets/images/payment/discover.svg',
      name: 'payment-discover',
      width: 75,
      height: 25,
    },
    {
      id: 5,
      path: '/',
      image: '/assets/images/payment/american_logo.svg',
      name: 'payment-american',
      width: 55,
      height: 25,
    },
  ],
  social: [
    {
      id: 1,
      path: 'https://www.facebook.com/',
      image: '/assets/images/social/facebook.svg',
      name: 'facebook',
      width: 20,
      height: 20,
    },
    {
      id: 2,
      path: 'https://twitter.com/',
      image: '/assets/images/social/twitter.svg',
      name: 'twitter',
      width: 20,
      height: 20,
    },
    {
      id: 3,
      path: 'https://www.instagram.com/',
      image: '/assets/images/social/instagram.svg',
      name: 'instagram',
      width: 20,
      height: 20,
    },
    {
      id: 4,
      path: 'https://www.youtube.com/',
      image: '/assets/images/social/youtube.svg',
      name: 'youtube',
      width: 20,
      height: 20,
    },
  ],
};
